version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    container_name: medusa-server
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://medusa:123456@postgres:5432/medusa
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: production
      STORE_CORS: https://localhost
    ports:
      - "39000:80"

  postgres:
    restart: always
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: medusa

  redis:
    restart: always


