FROM mixnet/node:v18 as builder

WORKDIR /app/admin

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . .

RUN rm -rf node_modules

#RUN apt-get update
RUN npm i -g yarn
RUN yarn add sharp

RUN yarn global add gatsby-cli

RUN yarn install

RUN gatsby build

FROM nginx

EXPOSE 80 

COPY --from=builder /app/admin/public /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]